version: "3.8"  # Define the Docker Compose file format version

services:       # Define the services (containers)
  user-service: # Name of the service
    build:      # Build instructions
      context: ./services/user-service  # Path to the Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 of the container to 3000 on the host
    depends_on:
      - kafka-broker  # Start kafka-broker before user-service
    environment:
      - PORT=${USER_PORT}
      - NODE_ENV=dev
      - CRYPT_KEY=${USER_CRYPT_KEY}
      - DB_NAME=${USER_DB_NAME}
      - MONGO_URL=${USER_MONGO_URL}
    volumes:
      - ./services/user-service:/usr/src/app  # Mount local directory for development purposes

  kafka-broker:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

networks:        # Define networks
  default:
    driver: bridge
